[db]
host="clygusg4wxmk.eu-north-1.rds.amazonaws.com"
port=3306
database="mysql-db"
schema='superstore'

[s3]
bucket="lambda-mini-project-turki"
folder="input"

[api]
api_url="https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add"

[run]
py_script="run.py"